<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $datos = [
            array( 
                'nombre' =>  "Tostadas con queso y Tomate",
                'precio' => 10.90,
                'imagen' => "desayuno_01",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Sandwich Club",
                'precio' => 12.90,
                'imagen' => "desayuno_02",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Wraps de Pollo y Aguacate",
                'precio' => 10.90,
                'imagen' => "desayuno_03",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Bol de Yogourt, Frutas y Cereales",
                'precio' => 9.50,
                'imagen' => "desayuno_04",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Gofres con Sirope",
                'precio' => 7.90,
                'imagen' => "desayuno_05",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Seleccion de Mini Croissants",
                'precio' => 12.90,
                'imagen' => "desayuno_06",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Brocheta de Frutas",
                'precio' => 6.90,
                'imagen' => "desayuno_07",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Café Capuccino",
                'precio' => 3.50,
                'imagen' => "desayuno_08",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Zumo de Naranja Natural",
                'precio' => 3.90,
                'imagen' => "desayuno_09",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Infusiones",
                'precio' => 3.00,
                'imagen' => "desayuno_10",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Seleccion de Jamón Iberico",
                'precio' => 15.00,
                'imagen' => "comida_01",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Ensalada de Atún",
                'precio' => 12.90,
                'imagen' => "comida_02",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Ensalada de Tomate y Mozzarella",
                'precio' => 12.90,
                'imagen' => "comida_03",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Penne Marinara",
                'precio' => 14.90,
                'imagen' => "comida_04",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Spaghuetti Carbonara",
                'precio' => 15.90,
                'imagen' => "comida_05",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Hamburguesa de Carne",
                'precio' => 15.90,
                'imagen' => "comida_06",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Iberico con Espinacas y Salsa Tariyaki",
                'precio' => 19.90,
                'imagen' => "comida_07",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Salmón con Verduras y Salsa Holandesa",
                'precio' => 19.90,
                'imagen' => "comida_08",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Tiramisú",
                'precio' => 7.00,
                'imagen' => "comida_09",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Tarta de Queso",
                'precio' => 7.00,
                'imagen' => "comida_10",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Seleccion de Jamón Iberico",
                'precio' => 15.00,
                'imagen' => "comida_01",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Ensalada de Atún",
                'precio' => 12.90,
                'imagen' => "comida_02",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Ensalada de Tomate y Mozzarella",
                'precio' => 12.90,
                'imagen' => "comida_03",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Penne Marinara",
                'precio' => 14.90,
                'imagen' => "comida_04",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Spaghuetti Carbonara",
                'precio' => 15.90,
                'imagen' => "comida_05",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Hamburguesa de Carne",
                'precio' => 15.90,
                'imagen' => "comida_06",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Iberico con Espinacas y Salsa Tariyaki",
                'precio' => 19.90,
                'imagen' => "comida_07",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Salmón con Verduras y Salsa Holandesa",
                'precio' => 19.90,
                'imagen' => "comida_08",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Tiramisú",
                'precio' => 7.00,
                'imagen' => "comida_09",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Tarta de Queso",
                'precio' => 7.00,
                'imagen' => "comida_10",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Copa Vino Blanco Seco",
                'precio' => 3.90,
                'imagen' => "bar_01",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Copa Vino Tinto Seco",
                'precio' => 3.90,
                'imagen' => "bar_02",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Copa Vino Blanco Afrutado",
                'precio' => 3.90,
                'imagen' => "bar_03",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Copa Vino Tinto Afrutado",
                'precio' => 3.90,
                'imagen' => "bar_04",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Copa de Cavae",
                'precio' => 4.90,
                'imagen' => "bar_05",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Copa de Cerveza",
                'precio' => 3.90,
                'imagen' => "bar_06",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Coca Cola",
                'precio' => 3.20,
                'imagen' => "bar_07",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Sprite",
                'precio' => 3.20,
                'imagen' => "bar_08",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Agua Natural",
                'precio' => 3.50,
                'imagen' => "bar_09",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Agua con Gas",
                'precio' => 3.50,
                'imagen' => "bar_10",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Hummus Clásico Mediterràneo",
                'precio' => 12.00,
                'imagen' => "menu_especial_01",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Hummus con Granada y Pepino",
                'precio' => 13.00,
                'imagen' => "menu_especial_02",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Crema de Calabaza",
                'precio' => 10.00,
                'imagen' => "menu_especial_03",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Sopa de Judias Blancas y Verduras",
                'precio' => 11.00,
                'imagen' => "menu_especial_04",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Cuscus con Mango y Espinaca",
                'precio' => 15.00,
                'imagen' => "menu_especial_05",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Rollitos de Primavera",
                'precio' => 12.00,
                'imagen' => "menu_especial_06",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Tortilla Vegana",
                'precio' => 12.00,
                'imagen' => "menu_especial_07",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Tagliatelle Sin Gluten con Champiñones",
                'precio' => 18.00,
                'imagen' => "menu_especial_08",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Hamburguesa Vegetal Sin Gluten",
                'precio' => 18.00,
                'imagen' => "menu_especial_09",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Gofres sin GLuten",
                'precio' => 8.00,
                'imagen' => "menu_especial_10",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
        ];

        DB::table('productos')->insert($datos);
    }
}
